name: Release Scheduler

on:
  schedule:
    - cron: '45 16 * * MON'
  workflow_dispatch:

env:
  PERFORM_SCHEDULED_RELEASES: true

jobs:
  prerequisites:
    name: Pre-requisites for building
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'sjohnr/gradle-test' }}
    outputs:
      runjobs: ${{ steps.continue.outputs.runjobs }}
    steps:
      - id: continue
        name: Determine if should continue
        run: |
          # Run jobs if in upstream repository
          echo "Setting runjobs=true"
          echo "::set-output name=runjobs::true"
  perform_scheduled_releases:
    name: Perform scheduled releases
    needs: [prerequisites]
    strategy:
      matrix:
        branch:
          - 'main'
          - '5.8.x'
          - '5.7.x'
          - '5.6.x'
    runs-on: ubuntu-latest
    if: ${{ needs.prerequisites.outputs.runjobs }}
    env:
      TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: sjohnr/spring-gradle-build-action@v1
      - name: Trigger release workflow
        if: ${{ env.PERFORM_SCHEDULED_RELEASES == 'true' }}
        run: ./gradlew triggerRelease -Pbranch=${{ matrix.branch }} -PgitHubAccessToken=$TOKEN
