name: Test Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: ['17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
      - name: Run Test
        run: |
          echo 'spring-builds+github' >> gradle.properties
          ./gradlew printUserName
