name: Test Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: ['17']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Run Test
        run: ./gradlew printUserName
