name: Test Workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sjohnr/spring-gradle-build-action@v1-beta
      - name: Run Test
        run: ./gradlew checkstyleNohttp
